//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_ProyectoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public Clase()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        public int Clase_id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Horario { get; set; }
        public Nullable<int> Capacidad { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
    }
}
