//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_ProyectoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int inscripcion_id { get; set; }
        public Nullable<int> miembro_id { get; set; }
        public Nullable<int> clase_id { get; set; }
        public Nullable<int> actividad_id { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public string estado_inscripcion { get; set; }
        public string detalles { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Clase Clase { get; set; }
        public virtual Miembro Miembro { get; set; }
    }
}
