//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_ProyectoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membresia
    {
        public Membresia()
        {
            this.Pago = new HashSet<Pago>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdMembresia { get; set; }
        public string TipoMembresia { get; set; }
        public decimal PrecioMembresia { get; set; }
    
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
