//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_ProyectoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Pago_id { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMembresia { get; set; }
        public System.DateTime Fecha_pago { get; set; }
        public decimal Monto { get; set; }
        public string Metodo_pago { get; set; }
    
        public virtual Membresia Membresia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
