//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_ProyectoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bitacora = new HashSet<Bitacora>();
            this.Clase = new HashSet<Clase>();
            this.Equipo = new HashSet<Equipo>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int IdUsuario { get; set; }
        public string CorreoElectronico { get; set; }
        public string Contrasenna { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public byte IdRol { get; set; }
        public bool UsaClaveTemporal { get; set; }
        public Nullable<int> IdMembresia { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
    
        public virtual ICollection<Bitacora> Bitacora { get; set; }
        public virtual ICollection<Clase> Clase { get; set; }
        public virtual ICollection<Equipo> Equipo { get; set; }
        public virtual Membresia Membresia { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
